# Do not put local implementation configuration here. Instead, put it in
# config/umlaut_config/database.yml
#
# Consult sample file in config/umlaut_distribution/database.yml-dist
#
# Try to remember to pay attention to char encoding, set encoding: utf8
# for mysql. 

  
<%= 
    # Load database config from the umlaut_config/database.yml local 
    # database config file, so it doesn't need to be in umlaut svn     
  lines = []  
  IO.foreach(RAILS_ROOT + "/config/umlaut_config/database.yml") {|l| lines << l}
  lines.join
%>
