# Global 'institution' reserved for services that
# aren't directly tied to a particular institution
global:
  default: true
  display_name: 
  services:
    - Crossref
    - Pubmed
    - Amazon
    - Google
    - Yahoo
    - YahooMyWeb
    - Connotea
    - CiteULike

# Define institution specific services here    
Georgia_Tech:
  default: true
  display_name: Georgia Tech
  services:
    - Opac
    - Opac2
    - GT_SFX
    - GT_EZProxy